name: CI
on: [push, pull_request]
jobs:
  lint:
    name: ✔️ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn lint
  build:
    name: 🛠️ Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn build
